# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

Name: Cao Han 
Student Number: 37255239

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [2]:
#IMPORT PANDAS TOOLS
import pandas as pd

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [3]:
# check directory
import os
# 3 layers up
print(os.listdir("../../data/hw/"))

['democracy_gdp.csv', 'ghg.csv']

In [4]:
democracy_gdp_filepath = "../../data/hw/democracy_gdp.csv"
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.head(4)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [5]:
ghg_file_path = "../../data/hw/ghg.csv"
ghg = pd.read_csv(ghg_file_path)
ghg.tail(3)

            Country  year     emissions
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [6]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [7]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= ['USA', 'CHN', 'DEU', 'FRA', 'JPN'],
)
gdp_data.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),China,CHN,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),China,CHN,2024,13303.148154,NaN,NaN,1

In [8]:
# check number of entries for each country
gdp_data['countryiso3code'].value_counts()

countryiso3code
CHN    36
DEU    36
FRA    36
JPN    36
USA    36
Name: count, dtype: int64

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [9]:
population_indicator = "SP.POP.TOTL"



country_list = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS"   # Australia
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
285,"Population, total",United States,USA,1992,256514000.0,NaN,NaN,0
286,"Population, total",United States,USA,1991,252981000.0,NaN,NaN,0
287,"Population, total",United States,USA,1990,249623000.0,NaN,NaN,0

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [10]:
# select countrycode column
gdp_data['countryiso3code'].head()

0    CHN
1    CHN
2    CHN
3    CHN
4    CHN
Name: countryiso3code, dtype: str

## 2.2 Filter Rows

Filter rows based on conditions.

In [11]:
# Show unique values in a column
gdp_data['countryiso3code'].unique()

<StringArray>
['CHN', 'DEU', 'FRA', 'JPN', 'USA']
Length: 5, dtype: str

In [12]:
# Filter using query
gdp_data.query("countryiso3code == 'JPN'").head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
108,GDP per capita (current US$),Japan,JPN,2025,NaN,NaN,NaN,1
109,GDP per capita (current US$),Japan,JPN,2024,32487.077805,NaN,NaN,1

In [13]:
gdp_data.query("date == 2020").head(5)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
5,GDP per capita (current US$),China,CHN,2020,10627.463799,NaN,NaN,1
41,GDP per capita (current US$),Germany,DEU,2020,47394.873450,NaN,NaN,1
77,GDP per capita (current US$),France,FRA,2020,39169.860600,NaN,NaN,1
113,GDP per capita (current US$),Japan,JPN,2020,40028.734173,NaN,NaN,1
149,GDP per capita (current US$),United States,USA,2020,63515.949181,NaN,NaN,1

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [14]:
# Filter with multiple conditions
# filter for Japan in 2020
gdp_data.query("countryiso3code == 'JPN' and date == 2020").head(1)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
113,GDP per capita (current US$),Japan,JPN,2020,40028.734173,NaN,NaN,1

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [15]:
# Filter Multiple and show unique countries
# You can either do one or two lines

# filter for multiple countries
gdp_data.query("countryiso3code in ['JPN', 'DEU']").head(5)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
36,GDP per capita (current US$),Germany,DEU,2025,NaN,NaN,NaN,1
37,GDP per capita (current US$),Germany,DEU,2024,56103.732318,NaN,NaN,1
38,GDP per capita (current US$),Germany,DEU,2023,54776.766824,NaN,NaN,1
39,GDP per capita (current US$),Germany,DEU,2022,50506.517964,NaN,NaN,1
40,GDP per capita (current US$),Germany,DEU,2021,52349.245999,NaN,NaN,1

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [21]:
# Filter rows and select columns
# japn and select date and value columns
gdp_data.query("countryiso3code == 'JPN'").filter(items=['date', 'value']).head(5)

     date         value
108  2025           NaN
109  2024  32487.077805
110  2023  33836.175627
111  2022  34065.643896
112  2021  40094.559980

## 2.6 Rename Columns

Rename columns in the dataframe.

In [17]:
# Before rename
democracy_gdp.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [ ]:
# Rename using rename with axis parameter

democracy_gdp.rename({'country': 'country_name'}, axis=1).head(2)
# axis=1 is the same as axis='columns' and axis=0 is the same as axis='index'

,country_name,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65